# test data - adm_subset

## Koch 6

k6 <- structure(
  list(
    registrationnb = c("XYZ1", "XYZ2", "XYZ3"),
    dstnumber = c(NA_character_,
                  NA_character_, NA_character_),
    registrationdate = c("02/12/2016",
                         "02/05/2017", "13/07/2016"),
    cdtbregister = c(2L, 2L, 2L),
    dateofbirth = c("2016-08-24",
                    "2017-01-22", "2016-04-04"),
    datedeat = c(NA_character_, NA_character_,
                 NA_character_),
    gender = c(2L, 1L, 2L),
    notdetected = c(0L, 0L,
                    0L),
    transferredin = c(0L, 0L, 0L),
    continuationdate = c(NA_character_,
                         NA_character_, NA_character_),
    cdhistory = c(1L, 1L, 1L),
    cdhistorydrugs = c(0L,
                       0L, 0L),
    cdsite = c(1L, 1L, 1L),
    cdsiteep = c(0L, 0L, 0L),
    cdsiteepoth = c(NA_character_,
                    NA_character_, NA_character_),
    cddetect = c(1L, 1L, 1L),
    cdsmear = 0:2,
    cdcult = c(0L, 1L, 1L),
    cdmolec = c(1L, 1L, 1L),
    cdstrainprofil = c(2L,
                       2L, 2L),
    cdstrainconf = c(5L, 5L, 5L),
    cdstrainconfoth = c(NA_character_,
                        NA_character_, NA_character_),
    cdhivenrol = c(2L, 2L, 2L),
    cdcpatenrol = c(0L, 0L, 0L),
    cdHivEnd = c(0L, 0L, 0L),
    cdCptEnd = c(0L,
                 0L, 0L),
    maritalstatus = c(3L, 3L, 3L),
    othermaritalstatus = c(NA_character_,
                           NA_character_, NA_character_),
    employement = c(3L, 3L, 3L),
    otheremployement = c(NA_character_, NA_character_, NA_character_),
    nbpeople = c(5L, 3L, 6L),
    nbchildren = c(1L, 0L, 2L),
    prison = c(0L, 0L, 0L),
    prisondate = c(NA_character_, NA_character_,
                   NA_character_),
    prisonnow = c(0L, 0L, 0L),
    Alcohol = c(0L,
                0L, 0L),
    IllicitDrug = c(NA_integer_, NA_integer_, NA_integer_),
    contactnotknown = c(0L, 1L, 0L),
    contacttb = c(0L, 0L,
                  1L),
    contactmdrcase = c(1L, 0L, 0L),
    homeless = c(0L, 0L,
                 0L),
    healthcare = c(0L, 0L, 0L),
    prisonworker = c(0L, 0L,
                     0L),
    migrant = c(0L, 0L, 0L),
    travel = c(0L, 0L, 0L),
    tabocca = c(0L,
                0L, 0L),
    prostitution = c(0L, 0L, 0L),
    otherrisk = c(0L,
                  0L, 0L),
    libelleotherrisk = c(NA_character_, NA_character_,
                         NA_character_),
    onsetsym = c(NA_character_, NA_character_,
                 NA_character_),
    dateval = c("29/11/2016", "26/04/2017", "11/07/2016"),
    weight = c(48L, 50L, 50L),
    height = c(1.62, 1.7, 1.62),
    BMI = c(18.3, 17.3, 19.1),
    fev = c(0L, 0L, 0L),
    sweats = c(0L,
               0L, 0L),
    drycough = c(0L, 0L, 0L),
    procough = c(0L, 0L, 0L),
    bloodspi = c(0L, 0L, 0L),
    chest = c(0L, 0L, 0L),
    lossapp = c(0L,
                0L, 0L),
    weigloss = c(0L, 0L, 0L),
    nausea = c(0L, 0L, 0L),
    vomiting = c(0L, 0L, 0L),
    diarrhoea = c(0L, 0L, 0L),
    dyspnea = c(0L,
                0L, 0L),
    headache = c(0L, 0L, 0L),
    visualpb = c(0L, 0L, 0L),
    hearingloss = c(0L, 0L, 0L),
    Numbness = c(0L, 0L, 0L),
    other1 = c(0L, 0L, 0L),
    other1descrip = c(NA_character_,
                      NA_character_, NA_character_),
    other2 = c(0L, 0L, 0L),
    other2descrip = c(NA_character_,
                      NA_character_, NA_character_),
    AudioAssessment = c(1L, 2L,
                        1L),
    AudioComment = c(NA_character_, NA_character_, NA_character_),
    ecgqt = c(320L, 320L, 360L),
    ecghr = c(0L, 0L, 0L),
    ecgrr = c(0.54,
              0.64, 0.56),
    ecgqtcf = c(393L, 371L, 437L),
    ecgComment = c(NA_character_,
                   NA_character_, NA_character_),
    pregnant = c(0L, 0L, 0L),
    contracept = c(0L, 0L, 0L),
    Pregtrimester = c(0L, 0L, 0L),
    previousTTR = c(2L, 2L, 2L),
    HowTb = c(0L, 0L, 0L),
    HowDR = c(0L,
              0L, 0L),
    LastDOTSID = c(NA_character_, NA_character_, NA_character_),
    priorSug = c(0L, 0L, 0L),
    priorSugDate = c(NA_character_,
                     NA_character_, NA_character_),
    diabetes = c(0L, 0L, 0L),
    diabinsu = c(0L, 0L, 0L),
    cardiodi = c(0L, 0L, 0L),
    seizure = c(0L,
                0L, 0L),
    seizmed = c(0L, 0L, 0L),
    renalfail = c(0L, 0L, 0L),
    hepadis = c(0L, 0L, 0L),
    hepChronic = c(0L, 0L, 0L),
    hepB = c(0L,
             0L, 0L),
    hepC = c(0L, 0L, 0L),
    HepOther = c(0L, 0L, 0L),
    pancrea = c(0L, 0L, 0L),
    pepticu = c(0L, 0L, 0L),
    silico = c(0L,
               0L, 0L),
    sarcoi = c(0L, 0L, 0L),
    copd = c(0L, 0L, 0L),
    psychi = c(0L,
               0L, 0L),
    depress = c(0L, 0L, 0L),
    er = c(0L, 0L, 0L),
    spfy = c(NA_character_,
             NA_character_, NA_character_),
    fushianb = c(NA_character_,
                 NA_character_, NA_character_),
    clistage = c(0L, 0L, 0L),
    hivRx = c(0L, 0L, 0L),
    hivRxStartdate = c(NA_character_,
                       NA_character_, NA_character_),
    drug1 = c(NA_character_, NA_character_,
              NA_character_),
    drug2 = c(NA_character_, NA_character_, NA_character_),
    drug3 = c(NA_character_, NA_character_, NA_character_),
    drug4 = c(NA_character_, NA_character_, NA_character_),
    XrayDate = c("23/11/2016",
                 NA, "08/06/2016"),
    XRay_Finding = c(2L, 0L, 2L),
    cav = c(0L,
            0L, 0L),
    cavD = c(0L, 0L, 0L),
    `Inf` = c(0L, 0L, 0L),
    InfD = c(0L,
             0L, 0L),
    tub = c(0L, 0L, 0L),
    tubD = c(0L, 0L, 0L),
    nodule = c(0L,
               0L, 0L),
    noduleD = c(0L, 0L, 0L),
    fib = c(0L, 0L, 0L),
    fibD = c(0L,
             0L, 0L),
    dis = c(0L, 0L, 0L),
    disD = c(0L, 0L, 0L),
    ple = c(0L,
            0L, 0L),
    pleD = c(0L, 0L, 0L),
    ade = c(0L, 0L, 0L),
    adeD = c(0L,
             0L, 0L),
    pne = c(0L, 0L, 0L),
    pneD = c(0L, 0L, 0L),
    miliary = c(0L,
                0L, 0L),
    cavsimple = c(1L, 0L, 2L),
    xraydatatype = c(2L,
                     0L, 2L),
    labClinDate = c("25/11/2016", "26/04/2017", "27/06/2016"),
    RBC = c(0L, 0L, 0L),
    WBC = c(7.9, 0, 8),
    Thrombocyt = c(0,
                   478, 414),
    Ers = c(0L, 0L, 0L),
    Hemoglobin = c(6.70248, 6.64042,
                   6.5163),
    Bilirubint = c(0L, 0L, 0L),
    Amylase = c(0L, 0L,
                0L),
    AST = c(0L, 0L, 0L),
    ALT = c(29, 11.7, 7.4),
    GGT = c(0L,
            0L, 0L),
    Aphosphata = c(0L, 0L, 0L),
    Creatkinas = c(0L, 0L,
                   0L),
    Creatinine = c(72, 65.4, 61),
    Urea = c(0L, 0L, 0L),
    Cholestero = c(0L, 0L, 0L),
    HDLcholest = c(0L, 0L, 0L),
    Glucose = c(4.1,
                4.02, 4.5),
    Trigglyceri = c(0L, 0L, 0L),
    Uricacid = c(0L,
                 0L, 0L),
    Potassium = c(5.5, 5.38, 4.05),
    Sodium = c(0L, 0L,
               0L),
    Magnesium = c(0L, 0L, 0L),
    Proteintot = c(0L, 0L, 0L),
    HIV = c(2L, 2L, 2L),
    CD4count = c(0L, 0L, 0L),
    Syphillis = c(0L,
                  0L, 0L),
    HepChronic = c(0L, 0L, 0L),
    HepB = c(0L, 2L, 2L),
    HepC = c(0L, 2L, 2L),
    BloodGr = c(0L, 0L, 0L),
    Rhesus = c(2L,
               2L, 2L),
    TSH = c(5.14, 0, 0),
    proteinUrin = c(0L, 0L, 0L),
    GlucUrin = c(0L, 0L, 0L),
    BloodUrin = c(0L, 0L, 0L),
    Lipase = c(0L,
               0L, 0L),
    InitialDR = c(1L, 1L, 1L),
    reas = c(0L, 0L, 0L),
    reasother = c(NA_character_, NA_character_, NA_character_),
    Starttre = c("02/12/2016", "03/05/2017", "16/07/2016"),
    Cohorte = c(20164L, 20172L, 20163L),
    Catregimen = c(2L, 2L,
                   2L),
    regimen1l = c(0L, 0L, 0L),
    regimen2l = c(8L, 8L, 8L),
    startgate = c("02/12/2016", "03/05/2017", "16/07/2016"),
    E = c(800L, 800L, 800L),
    H = c(400L, 400L, 400L),
    R = c(NA_integer_,
          NA_integer_, NA_integer_),
    Z = c(1600L, 1600L, 1600L),
    Am = c(NA_character_,
           NA_character_, NA_character_),
    Cm = c(750L, 750L, 750L),
    Km = c(NA_integer_, NA_integer_, NA_integer_),
    S = c(NA_character_,
          NA_character_, NA_character_),
    Vi = c(NA_character_, NA_character_,
           NA_character_),
    Cfx = c(NA_character_, NA_character_, NA_character_),
    Gfx = c(NA_character_, NA_character_, NA_character_),
    Lfx = c(NA_integer_, NA_integer_, NA_integer_),
    Mfx = c(400L,
            400L, 400L),
    Ofx = c(NA_character_, NA_character_, NA_character_),
    Cs = c(NA_integer_, NA_integer_, NA_integer_),
    Eto = c(NA_character_,
            NA_character_, NA_character_),
    PAS = c(NA_integer_, NA_integer_,
            NA_integer_),
    `PAS Na` = c(NA_character_, NA_character_,
                 NA_character_),
    Pto = c(500L, 500L, 500L),
    Trd = c(NA_character_,
            NA_character_, NA_character_),
    `Amx-Clv` = c(NA_integer_,
                  NA_integer_, NA_integer_),
    Bdq = c(NA_character_, NA_character_,
            NA_character_),
    Cfz = c(100L, 100L, 100L),
    Clr = c(NA_character_,
            NA_character_, NA_character_),
    Dld = c(NA_character_, NA_character_,
            NA_character_),
    hdH = c(NA_character_, NA_character_, NA_character_),
    ImpCln = c(NA_character_, NA_character_, NA_character_),
    Lzd = c(NA_integer_, NA_integer_, NA_integer_),
    Mpm = c(NA_character_,
            NA_character_, NA_character_),
    Thz = c(NA_character_, NA_character_,
            NA_character_),
    dateend = c(NA, NA, "14/04/2017"),
    dateout = c(NA,
                NA, "09/06/2017"),
    outfirst = c(0L, 0L, 1L),
    outother = c(NA_character_,
                 NA_character_, NA_character_),
    outseconddefaulter = c(0L,
                           0L, 0L),
    outsecondfailure = c(0L, 0L, 0L),
    previoustransfout = c(0L,
                          0L, 0L),
    defaultbehav = c(0L, 0L, 0L),
    `2013outcome` = c(NA_character_,
                      NA_character_, NA_character_),
    outfirst2013 = c(0L, 0L, 0L),
    outother2013 = c(NA_character_, NA_character_, NA_character_),
    interrupt2013 = c(0L, 0L, 0L),
    interrupt2013oth = c(NA_character_,
                         NA_character_, NA_character_),
    failure2013 = c(0L, 0L, 0L),
    failampli = c(0L, 0L, 0L),
    faillack = c(0L, 0L, 0L),
    failrevers = c(0L,
                   0L, 0L),
    Failure2013ClinComment = c(NA_character_, NA_character_,
                               NA_character_),
    deatcaus = c(0L, 0L, 0L),
    outcomenotvalidated = c(0L,
                            0L, 0L),
    endip = c("22/04/2017", NA, "16/11/2016"),
    smearconv = c(NA_character_,
                  NA_character_, NA_character_),
    cultconv = c(NA_character_,
                 NA_character_, NA_character_),
    ENDHOSP = c(NA_character_,
                NA_character_, NA_character_),
    X242 = c(NA_character_, NA_character_,
             NA_character_),
    X243 = c(NA_character_, NA_character_, NA_character_),
    X244 = c(NA_character_, NA_character_, NA_character_),
    X245 = c(NA_character_, NA_character_, NA_character_),
    X246 = c(NA_character_,
             NA_character_, NA_character_),
    X247 = c(NA_character_, NA_character_,
             NA_character_),
    X248 = c(NA_character_, NA_character_, NA_character_),
    X249 = c(NA_character_, NA_character_, NA_character_),
    X250 = c(NA_character_, NA_character_, NA_character_),
    X251 = c(NA_character_,
             NA_character_, NA_character_),
    X252 = c(NA_character_, NA_character_,
             NA_character_),
    X253 = c(NA_character_, NA_character_, NA_character_),
    X254 = c(NA_character_, NA_character_, NA_character_),
    X255 = c(NA_character_, NA_character_, NA_character_),
    X256 = c(NA_character_,
             NA_character_, NA_character_),
    X257 = c(NA_character_, NA_character_,
             NA_character_),
    X258 = c(NA_character_, NA_character_, NA_character_),
    X259 = c(NA_character_, NA_character_, NA_character_),
    X260 = c(NA_character_, NA_character_, NA_character_),
    X261 = c(NA_character_,
             NA_character_, NA_character_),
    X262 = c(NA_character_, NA_character_,
             NA_character_),
    X263 = c(NA_character_, NA_character_, NA_character_),
    X264 = c(NA_character_, NA_character_, NA_character_),
    X265 = c(NA_character_, NA_character_, NA_character_),
    X266 = c(NA_character_,
             NA_character_, NA_character_),
    X267 = c(NA_character_, NA_character_,
             NA_character_),
    X268 = c(NA_character_, NA_character_, NA_character_),
    X269 = c(NA_character_, NA_character_, NA_character_),
    X270 = c(NA_character_, NA_character_, NA_character_),
    X271 = c(NA_character_,
             NA_character_, NA_character_),
    X272 = c(NA_character_, NA_character_,
             NA_character_),
    X273 = c(NA_character_, NA_character_, NA_character_),
    X274 = c(NA_character_, NA_character_, NA_character_),
    X275 = c(NA_character_, NA_character_, NA_character_),
    X276 = c(NA_character_,
             NA_character_, NA_character_),
    X277 = c(NA_character_, NA_character_,
             NA_character_),
    X278 = c(NA_character_, NA_character_, NA_character_),
    X279 = c(NA_character_, NA_character_, NA_character_),
    X280 = c(NA_character_, NA_character_, NA_character_),
    X281 = c(NA_character_,
             NA_character_, NA_character_)
  ),
  row.names = c(NA,-3L),
  class = c("tbl_df",
            "tbl", "data.frame")
)
saveRDS(k6, "inst/testdata/adm_subset_koch6.rds", version = 2)


# EpiInfo


epi <- structure(
  list(
    SURNAME = c("XXYYZZ", "XXYYZZ", "XXYYZZ"),
    APID = c("ZZZ1",
             "ZZZ2", "ZZZ3"),
    NAME = c("AABBCC", "AABBCC", "AABBCC"),
    BIRTDATE = c("01/01/2014",
                 "01/01/2014", "01/01/2014"),
    ADDRESS = c("HHIIJJ", "HHIIJJ",
                "HHIIJJ"),
    PHON = c(NA_character_, NA_character_, NA_character_),
    SEX = c("F", "M", "M"),
    NUMBEO = c("12", "8", "6"),
    NUMCHI = c("5",
               "4", "2"),
    NUMCHI14 = c(NA_character_, NA_character_, NA_character_),
    MARISTAT = c("1", "4", "1"),
    EMPL = c("4", "4", "2"),
    EVER = c("N",
             "Y", "N"),
    INJECT = c("N", "N", "N"),
    ALCO = c("1", "0", "0"),
    HOMELESS = c(NA_character_, NA_character_, NA_character_),
    HEALTHWO = c("Y", NA, NA),
    PRIWO = c(NA_character_, NA_character_,
              NA_character_),
    TRAVELR = c(NA, "Y", NA),
    TOBACCO = c(NA,
                "Y", "Y"),
    CONTACT = c(NA_character_, NA_character_, NA_character_),
    CONTACTTB = c(NA_character_, NA_character_, NA_character_),
    P2APID = c("ZZZ1", "ZZZ2", "ZZZ3"),
    Z1 = c("R", "R", "R"),
    REGRP = c("2", "5", "5"),
    PRETRAPID = c(NA_character_,
                  NA_character_, NA_character_),
    DEFREG = c(NA_character_,
               NA_character_, NA_character_),
    PREVAP = c(NA_character_,
               NA_character_, NA_character_),
    ONSETSYM = c("01/11/2001",
                 "01/02/1994", "01/10/2000"),
    NUMPRETR = c("6", "4", "6"),
    ST1 = c("27/11/2001", "19/10/2001", "09/04/2001"),
    RG1 = c("1",
            "2", "2"),
    TY1 = c("1", "1", "1"),
    OT1 = c("1", "4", "4"),
    ST2 = c(NA_character_, NA_character_, NA_character_),
    RG2 = c(NA_character_,
            NA_character_, NA_character_),
    TY2 = c(NA_character_, NA_character_,
            NA_character_),
    OT2 = c(NA_character_, NA_character_, NA_character_),
    ST3 = c(NA_character_, NA_character_, NA_character_),
    RG3 = c(NA_character_, NA_character_, NA_character_),
    TY3 = c(NA_character_,
            NA_character_, NA_character_),
    OT3 = c(NA_character_, NA_character_,
            NA_character_),
    ST4 = c(NA_character_, NA_character_, NA_character_),
    RG4 = c(NA_character_, NA_character_, NA_character_),
    TY4 = c(NA_character_, NA_character_, NA_character_),
    OT4 = c(NA_character_,
            NA_character_, NA_character_),
    ST5 = c(NA_character_, NA_character_,
            NA_character_),
    RG5 = c(NA_character_, NA_character_, NA_character_),
    TY5 = c(NA_character_, NA_character_, NA_character_),
    OT5 = c(NA_character_, NA_character_, NA_character_),
    ST6 = c(NA_character_,
            NA_character_, NA_character_),
    RG6 = c(NA_character_, NA_character_,
            NA_character_),
    TY6 = c(NA_character_, NA_character_, NA_character_),
    OT6 = c(NA_character_, NA_character_, NA_character_),
    HD = c("Y", "Y", "Y"),
    EE = c("Y", "Y", "Y"),
    RR = c("Y",
           "Y", "Y"),
    ZP = c("Y", "Y", "Y"),
    CSC = c(NA_character_,
            NA_character_, NA_character_),
    SMS = c("Y", "Y", "Y"),
    AMA = c(NA_character_,
            NA_character_, NA_character_),
    KMK = c(NA, "Y", "Y"),
    CPX = c(NA_character_,
            NA_character_, NA_character_),
    OFX = c(NA_character_, NA_character_,
            NA_character_),
    TT = c(NA_character_, NA_character_, NA_character_),
    ETHE = c(NA_character_, NA_character_, NA_character_),
    PASP = c(NA_character_, NA_character_, NA_character_),
    AMXC = c(NA_character_,
             NA_character_, NA_character_),
    CFZ = c(NA_character_, NA_character_,
            NA_character_),
    CLRC = c(NA_character_, NA_character_, NA_character_),
    CMC = c(NA_character_, NA_character_, NA_character_),
    OTH = c(NA_character_, NA_character_, NA_character_),
    SPE1 = c(NA_character_,
             NA_character_, NA_character_),
    P3APID = c("ZZZ1", "ZZZ2",
               "ZZZ3"),
    WEIGHT = c("55", "60", "46"),
    HEIGHT = c("1.7",
               "1.76", "1.72"),
    SITEDIS = c("1", "1", "1"),
    XRAYRES = c("2",
                "2", "2"),
    ABNORM = c("1", "1", "1"),
    HIV = c("3", "3", "3"),
    ARV = c(NA_character_, NA_character_, NA_character_),
    ARVDT = c(NA_character_, NA_character_, NA_character_),
    CO1 = c("05/01/2004",
            "28/01/2004", "11/12/2003"),
    NB1 = c("108", "132", "81"),
    RES1 = c("3", "3", "3"),
    CRE1 = c("2", "2", "2"),
    MET = c("2",
            "2", "2"),
    H1 = c("R", "R", "R"),
    E1 = c("R", "R", "R"),
    R1 = c("R", "R", "R"),
    S1 = c("R", "R", "R"),
    Z101 = c(NA_character_,
             NA_character_, NA_character_),
    K1 = c("S", "S", "S"),
    CAP1 = c("S",
             "S", "S"),
    OFL1 = c("S", "S", "S"),
    MFX1 = c(NA_character_,
             NA_character_, NA_character_),
    ETH1 = c("S", "S", "S"),
    CS1 = c("S",
            "S", "S"),
    PAS1 = c("S", "S", "S"),
    DIPRO = c("4", "4", "4"),
    DATEDST = c("07/05/2004", "07/05/2004", "11/03/2004"),
    ADMIDATE = c("03/01/2004", "02/02/2004", "02/02/2004"),
    STARTTRE = c("08/01/2004",
                 "05/02/2004", "05/02/2004"),
    CATTRE = c("4", "4", "4"),
    DIABETES = c(NA_character_,
                 NA_character_, NA_character_),
    CARDIODI = c(NA_character_,
                 NA_character_, NA_character_),
    RENALFAI = c(NA_character_,
                 NA_character_, NA_character_),
    PSYCHI = c(NA_character_,
               NA_character_, NA_character_),
    SEIZURE = c(NA_character_,
                NA_character_, NA_character_),
    HEPADIS = c(NA_character_,
                NA_character_, NA_character_),
    OTHER = c(NA_character_, NA_character_,
              NA_character_),
    SPFY = c(NA_character_, NA_character_, NA_character_),
    P4APID = c("XYZ0003", "XYZ0004", "XYZ0005"),
    CO2 = c("05/01/2004",
            "03/02/2004", "03/02/2004"),
    NB2 = c("04-00108", "04-00142",
            "04-00139"),
    RES2 = c("1", "1", "1"),
    CRE2 = c("2", "2",
             "2"),
    MET2 = c(NA_character_, NA_character_, NA_character_),
    HA = c(NA_character_, NA_character_, NA_character_),
    EA = c(NA_character_,
           NA_character_, NA_character_),
    RA = c(NA_character_, NA_character_,
           NA_character_),
    SA = c(NA_character_, NA_character_, NA_character_),
    ZA = c(NA_character_, NA_character_, NA_character_),
    KA = c(NA_character_,
           NA_character_, NA_character_),
    CAPA = c(NA_character_, NA_character_,
             NA_character_),
    OFLA = c(NA_character_, NA_character_, NA_character_),
    MFXA = c(NA_character_, NA_character_, NA_character_),
    ETHA = c(NA_character_, NA_character_, NA_character_),
    CSA = c(NA_character_,
            NA_character_, NA_character_),
    PASA = c(NA_character_, NA_character_,
             NA_character_),
    DATEDST2 = c(NA_character_, NA_character_,
                 NA_character_),
    ENDHOSP = c("20/01/2004", "13/10/2004", "24/09/2004"),
    ADRP = c("4", NA, NA),
    APIDL = c("XYZ000308012004", "XYZ000405022004",
              "XYZ000505022004"),
    P5APID = c("XYZ0003", "XYZ0004", "XYZ0005"),
    HDH = c(NA_character_, NA_character_, NA_character_),
    RDR = c(NA_character_, NA_character_, NA_character_),
    DLMDDLM = c(NA_character_,
                NA_character_, NA_character_),
    EDE = c(NA_character_, NA_character_,
            NA_character_),
    ZDZ = c(NA, NA, "1500"),
    SDS = c(NA_character_,
            NA_character_, NA_character_),
    KADKA = c("1000", NA, NA),
    OFLDOFL = c("800", "800", "800"),
    CAPDCAP = c(NA, "1000",
                "750"),
    ETHDETH = c("1000", "750", "500"),
    CYCLDCYCL = c("750",
                  "750", "500"),
    AMXDAMX = c("1875", "1875", NA),
    PASDPAS = c("10000",
                "8000", "8000"),
    CLADCLA = c(NA_character_, NA_character_,
                NA_character_),
    CLODCLO = c(NA_character_, NA_character_,
                NA_character_),
    LXDLX = c(NA_character_, NA_character_, NA_character_),
    MXDMX = c(NA_character_, NA_character_, NA_character_),
    PTDPT = c(NA_character_, NA_character_, NA_character_),
    LZDDLZD = c(NA_character_,
                NA_character_, NA_character_),
    IMPDIMP = c(NA_character_,
                NA_character_, NA_character_),
    BDQDBDQ = c(NA_character_,
                NA_character_, NA_character_),
    LI = c("POS", "POS", "POS"),
    PHA = c("1", "1", "1"),
    CONSDAY1 = c(NA_character_, NA_character_,
                 NA_character_),
    INAMB1 = c(NA_character_, NA_character_,
               NA_character_),
    P6APID = c("XYZ0003", "XYZ0004", "XYZ0005"),
    INTPD = c(NA, "6", "6"),
    CO3 = c(NA, "23/08/2004", "03/08/2004"),
    ILB = c(NA, "04-00481", "04-00440"),
    ISM = c(NA, "0",
            "0"),
    ICT = c(NA, "3", "3"),
    IDTEST = c(NA_character_, NA_character_,
               NA_character_),
    HI = c(NA_character_, NA_character_, NA_character_),
    EI = c(NA_character_, NA_character_, NA_character_),
    RI = c(NA_character_,
           NA_character_, NA_character_),
    SI = c(NA_character_, NA_character_,
           NA_character_),
    ZI = c(NA_character_, NA_character_, NA_character_),
    KI = c(NA_character_, NA_character_, NA_character_),
    CAPI = c(NA_character_,
             NA_character_, NA_character_),
    OFLI = c(NA_character_, NA_character_,
             NA_character_),
    MFXI = c(NA_character_, NA_character_, NA_character_),
    ETHI = c(NA_character_, NA_character_, NA_character_),
    CSI = c(NA_character_, NA_character_, NA_character_),
    PASI = c(NA_character_,
             NA_character_, NA_character_),
    IDRP = c(NA_character_, NA_character_,
             NA_character_),
    KINDDATA = c(NA, NA, "3"),
    P7APID = c("XYZ0003",
               "XYZ0004", "XYZ0005"),
    DATEN = c("20/01/2004", "31/01/2006",
              "22/12/2005"),
    RES = c("5", "1", "1"),
    NEWAPID = c(NA_character_,
                NA_character_, NA_character_),
    DATEDEAT = c(NA_character_,
                 NA_character_, NA_character_),
    TRANDT = c(NA_character_,
               NA_character_, NA_character_),
    OUTD = c(NA_character_, NA_character_,
             NA_character_),
    SCONV = c(NA_character_, NA_character_, NA_character_),
    SMEARI = c(NA_character_, NA_character_, NA_character_),
    SMEARN = c(NA, "03/06/2004", "14/06/2004"),
    P8APID = c("XYZ0003",
               "XYZ0004", "XYZ0005"),
    CCONV = c(NA_character_, NA_character_,
              NA_character_),
    CULTI = c(NA_character_, NA_character_, NA_character_),
    CULTN = c(NA, "05/04/2004", "05/04/2004"),
    CO4 = c(NA_character_,
            NA_character_, NA_character_),
    LLB = c(NA_character_, NA_character_,
            NA_character_),
    LDTEST = c(NA_character_, NA_character_,
               NA_character_),
    HL = c(NA_character_, NA_character_, NA_character_),
    EL = c(NA_character_, NA_character_, NA_character_),
    RL = c(NA_character_,
           NA_character_, NA_character_),
    SL = c(NA_character_, NA_character_,
           NA_character_),
    ZL = c(NA_character_, NA_character_, NA_character_),
    KL = c(NA_character_, NA_character_, NA_character_),
    CAPL = c(NA_character_,
             NA_character_, NA_character_),
    OFLL = c(NA_character_, NA_character_,
             NA_character_),
    MFXL = c(NA_character_, NA_character_, NA_character_),
    ETHL = c(NA_character_, NA_character_, NA_character_),
    CSL = c(NA_character_, NA_character_, NA_character_),
    PASL = c(NA_character_,
             NA_character_, NA_character_),
    LDRP = c(NA_character_, NA_character_,
             NA_character_),
    HOSP = c(NA_character_, NA_character_, NA_character_),
    SIDEEFF = c(NA_character_, NA_character_, NA_character_),
    CLINDET = c(NA_character_, NA_character_, NA_character_),
    OTHE = c(NA_character_, NA_character_, NA_character_),
    SPECOTHE = c(NA_character_, NA_character_, NA_character_)
  ),
  class = c("tbl_df",
            "tbl", "data.frame"),
  row.names = c(NA,-3L)
)

saveRDS(epi, "inst/testdata/adm_subset_epi.rds", version = 2)
