# Test data for lab_subset()

## Grozny lab data
structure(list(dbno = 1L, dstno = "XYZ-1000", labno = 1957L, 
               surname = "______", firstname = "_______", dob = "26/10/1961", 
               age = 51L, gender = "M", address = "________, __. ______,3", 
               region = "____________", refsite = "Dispensary", tbprog = "MoH", 
               tbno = NA_character_, samptype = "Diagnostic", sampdiag = "Previously treated 1st line-Relapse", 
               fumonth = NA_character_, doctor = NA_character_, sputum = "Sputum-Deep cough", 
               samptype_1 = NA_character_, testreq = "Microscopy/Culture/DST", 
               dstreq = "1st line", dcol1 = "18/06/2012", drec1 = "19/06/2012", 
               sampqual1 = "Sputum", micro1 = "2+", dcol2 = "19/06/2012", 
               drec2 = "19/06/2012", sampqual2 = "Sputum", micro2 = "3+", 
               dcol3 = "19/06/2012", drec3 = "19/06/2012", sampqual3 = "Sputum", 
               micro3 = "3+", dres = "20/06/2012", micres = "Positive", 
               drop1 = "Positive", drop2 = "Positive", drop3 = "Positive", 
               dcolxpert1 = NA_character_, dcolxpert2 = NA_character_, drecxpert1 = NA_character_, 
               drecxpert2 = NA_character_, samxpertqual1 = NA_character_, 
               samxpertqual2 = NA_character_, dxpertres1 = NA_character_, 
               dxpertres2 = NA_character_, tatxpert1 = NA_character_, tatxpert2 = NA_character_, 
               qcspcxpert1 = NA_character_, qcpccxpert1 = NA_character_, 
               qcspcxpert2 = NA_character_, qcpccxpert2 = NA_character_, 
               xpert1err = NA_character_, xpert1errcd = NA_real_, xpertmdno1 = NA_character_, 
               xpert2err = NA_character_, xpert2errcd = NA_character_, xpertmdno2 = NA_character_, 
               xpert1res = NA_character_, xpert2res = NA_character_, xpert1rif = NA_character_, 
               xpert2rif = NA_character_, xpertrpt = NA_character_, xpertrptreas = NA_character_, 
               xpertcomm = NA_character_, mgit1d = "19/06/2012", mgit2d = "20/06/2012", 
               mgit3d = NA_character_, mgit1rep = "25/06/2012", mgit2rep = "27/06/2012", 
               mgit3rep = "10/07/2012", drop5 = "Positive", drop6 = "Positive", 
               drop7 = "Positive", mgitres = "Positive", drop8 = "Positive", 
               drop9 = "Positive", drop10 = "Positive", mg_zn1id = "Pos", 
               mg_mpt641id = "Pos", mg_bhi1id = "Neg", mg_id1res = "MTBc", 
               mg_zn2id = "Pos", mg_mpt642id = "Pos", mg_bhi2id = NA_character_, 
               mg_id2res = "MTBc", ms = "S", mh = "S", mr = "S", me = "S", 
               mz = NA_character_, mcm = NA_character_, mkm = NA_character_, 
               mam = NA_character_, mofx = NA_character_, mlfx = NA_character_, 
               mcs = NA_character_, meth = NA_character_, mpto = NA_character_, 
               mpas = NA_character_, mgdst1res = "Sensitive", mgdst1stt = NA_character_, 
               mgdst1d = "23/07/2012", lj1d = "19/06/2012", lj2d = "19/06/2012", 
               lj3d = NA_character_, lj1resd = "20/07/2012", lj2resd = "20/07/2012", 
               lj3resd = NA_character_, drop11 = "Positive", drop12 = "Positive", 
               drop13 = NA_character_, ljres = "Positive", drop14 = "Positive", 
               drop15 = "Positive", drop16 = NA_character_, lj_id1res = "Pos", 
               ljzn2id = "Pos", ljmpt642id = NA_character_, ljtch2id = NA_character_, 
               ljsss2id = "MTBc", lj_id2res = "Pos", drop17 = "Pos", drop18 = NA_character_, 
               drop19 = NA_character_, drop20 = "MTBc", ljs = "S", ljh = "S", 
               ljr = "S", lje = "S", ljz = NA_character_, ljcm = NA_character_, 
               ljkm = NA_character_, ljam = NA_character_, ljofx = NA_character_, 
               ljlfx = NA_character_, ljcs = NA_character_, ljeth = NA_character_, 
               ljpto = NA_character_, ljpas = NA_character_, ljdst1res = "Sensitive", 
               ljdst2res = NA_character_, ljdstd = "20/08/2012", dctsent = "25/06/2012", 
               ctmicd = "07/10/2012", ctmicres = "3+", ctmgitd = "10/07/2012", 
               ctmgitres = "Positive", ctidd = "10/07/2012", ctidres = "MTBc", 
               ctmgdstd = "26/07/2013", cts = "S", cth = "S", ctr = "S", 
               cte = "S", ctz = "S", ctcm = "S", ctkm = NA_character_, ctam = "S", 
               ctofx = NA_character_, ctlfx = "S", ctmfx = NA_character_, 
               ctmfx2 = NA_character_, ctcs = NA_character_, cteth = "S", 
               ctpto = NA_character_, ctpas = NA_character_, ctlzd = NA_character_, 
               ctdstres = "Sensitive", cthd = "10/07/2012", cthres = "Pos", 
               cthrpobwt = "Pos", cthrpobmut = "Neg", cthkatgwt = "Pos", 
               cthkatgmut = "Neg", cthinhawt = "Pos", cthinhamut = "Neg", 
               cthrifres = "S", cthinhres = "S"), row.names = c(NA, -1L), class = c("tbl_df", 
                                                                                    "tbl", "data.frame", "grozny"))
